### ISSUE TITLE
playlist file not created

### ISSUE THREAD

**Issue by regulator-g** [caseychu/spotify-backup#12]
Hi, in the instructions it doesnt say where the file you create will be saved?

when I run the script it works, i can see its finding my playlists but then it exits and I cant find the file it was supposedly creating

also when i run it in "IDLE" i get this:
Enter a file name (e.g. playlists.txt): c:\temp\tg.txt
Traceback (most recent call last):
  File "C:\temp\spotify-backup.py", line 170, in <module>
    main()
  File "C:\temp\spotify-backup.py", line 141, in main
    log('Logged in as {display_name} ({id})'.format(**me))
  File "C:\temp\spotify-backup.py", line 115, in log
    sys.stdout.buffer.write('[{}] {}\n'.format(time.strftime('%I:%M:%S'), str).encode(sys.stdout.encoding, errors='replace'))
AttributeError: 'PseudoOutputFile' object has no attribute 'buffer'
>>>

**Comment by Sogolumbo** [comment]
The file gets saved in the working directory. Often that's where the python file is located but it can end up anywhere else depending on how you run the file.

**Comment by caseychu** [comment]
This was an issue with logging, fixed.
