### ISSUE TITLE
Error in log function + workaround

### ISSUE THREAD

**Issue by GregoryGleibman** [caseychu/spotify-backup#17]
Hi, I got this error:
`line 115, in log
    sys.stdout.buffer.write('[{}] {}\n'.format(time.strftime('%I:%M:%S'), str).encode(sys.stdout.encoding, errors='replace'))
AttributeError: 'PseudoOutputFile' object has no attribute 'buffer'`

As a workaround, I disabled this function.

Also, I suggest adding to readme.md: 

**Your liked songs won't be saved by this script, unless you convert them to a playlist. You can do it by selecting all liked songs in Spotify for Windows, by pressing ctrl+A, and then right click and add to playlist.**

Thanks for this script, it helped me avoid user lock in, and I could cancel Spotify without losing my data.

**Comment by caseychu** [comment]
Fixed!
