### ISSUE TITLE
liked songs

### ISSUE THREAD

**Issue by Gahamelas** [caseychu/spotify-backup#18]
Are "liked songs" copied as a playlist? I couldn't find my liked songs in the exported file.
Otherwise, awesome tool.

**Comment by lamorton** [comment]
It looks like the "liked" songs are located at:
https://open.spotify.com/user/{user_id}/collection

I tried substituting 'collection' for 'playlists' in the code, but it doesn't work.  There's nothing in the Spotify API reference about it.

**Comment by lamorton** [comment]
Yes, version I wrote [here](https://github.com/lamorton/spotify-backup/tree/liked_songs) implements the fix.

**Comment by Gahamelas** [comment]
So it hasn't been merged in the master?

**Comment by lamorton** [comment]
Ahh, sorry, I linked you to the master instead of [feature branch](https://github.com/lamorton/spotify-backup/tree/liked_songs).  Note that you need to use the command as

```python spotify-backup.py --scope user-library-read```

**Comment by Gahamelas** [comment]
Thanks! If I do  

`python spotify-backup.py playlists.txt  `

it won't work?
Also, what heading do the liked songs have? I can't find them (I have over 2000 tracks!).

**Comment by lamorton** [comment]
You can put the filename at the end, but you need the ` --scope user-library-read` part in there to get the liked songs -- and then it will *only* get the liked songs, no other playlists.

**Comment by lamorton** [comment]
Btw, it looks like [this fork](https://github.com/Alex131089/spotify-backup) has even more features.

**Comment by Gahamelas** [comment]
Thanks so much!

**Comment by Gahamelas** [comment]
> You can put the filename at the end, but you need the ` --scope user-library-read` part in there to get the liked songs -- and then it will _only_ get the liked songs, no other playlists.

BTW, it won't work for me.
`spotify-backup.py: error: argument --scope: invalid choice: 'user-library-read' (choose from 'playlist-read-private', 'playlist-read-collaborative')`
