### ISSUE TITLE
SAVED songs and albums

### ISSUE THREAD

**Issue by AtomicNess123** [caseychu/spotify-backup#19]
Does this script also save the "SAVED" albums and tracks thereof? Thanks!

**Comment by Sogolumbo** [comment]
Currently it does not save those.
There are two pull requests that return the saved tracks but not the saved albums.

**Comment by IR13s** [comment]
https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-saved-albums

maybe this helps.

**Comment by peterrus** [comment]
Hi, I implemented this in https://github.com/caseychu/spotify-backup/pull/41

**Comment by AtomicNess123** [comment]
Is it accesible via git clone already? I don't see it updated.

**Comment by peterrus** [comment]
@AtomicNess123 You should be able to check it out using:
```
git clone https://github.com/peterrus/spotify-backup.git
cd spotify-backup
git checkout feature/liked-albums
```

**Comment by AtomicNess123** [comment]
It did not work. I did not save my LIKED songs.
