### ISSUE TITLE
TypeError while writing files

### ISSUE THREAD

**Issue by hugolundin** [caseychu/spotify-backup#31]
Hi! Thank you for making a really useful script :)
I used it a couple of months ago with no issues, but after merging
the latest changes from master I get the following error: 

```bash
[08:44:09] Writing files...
Traceback (most recent call last):
  File "<path>/spotify-backup.py", line 201, in <module>
    main()
  File "<path>/spotify-backup.py", line 192, in main
    uri=track['track']['uri'],
TypeError: 'NoneType' object is not subscriptable
```

Any suggestions? Thanks!

**Comment by caseychu** [comment]
Thanks for pointing this out! Should be fixed by https://github.com/caseychu/spotify-backup/pull/30

**Comment by hugolundin** [comment]
Awesome, thanks!
