### ISSUE TITLE
Requires Python 3

### ISSUE THREAD

**Issue by vbuzzegoli** [caseychu/spotify-backup#39]
Quick suggestion. As this code requires Python 3+ the commands indicated might fail if `python` uses v2 by default.
It may be good to document that or to advocate using `python3` instead of `python`.

**Comment by jogama** [comment]
@vbuzzegoli do you mean to point out that the README.md uses `python` instead of `python3` in its examples, and thus may produce errors on systems where `python==python2`?

**Comment by rfong** [comment]
Also would be nice if the minor version was documented. For me it failed on Python 3.5.2 but worked fine when I switched to Python 3.8.1. (I didn't end up binary searching to figure out the author's exact version.)

**Comment by vrnvorona** [comment]
> Python 2 has reached its end-of-life some time ago and has no form of support whatsoever. Distributions still packaging it should really update, it's been many years that Python 3 has been the norm.
> 
> This caveat probably only applies to very old, outdated, legacy systems.

Even recent macOS uses python2 as default python, while install python 3.x is python3.

Doesn't hurt anyone to use python3 command
