### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by vladh** [caseychu/spotify-backup#48]
Hi!

Could you please add a license, so that others are free to fully use this code?

If you wanted to use GPLv3 for example, you could save this file into the repo with the name `LICENSE`. https://www.gnu.org/licenses/gpl-3.0.txt

Thanks!

**Comment by jack-mil** [comment]
Hi, new guy here. I am also looking to fork and make some modifications and update of the code. I don't won't to make the fork public without a license. If you are still maintaining this, an open-source license would be great! 
MIT is what I usually go with for small projects like this

**Comment by caseychu** [comment]
Thanks for the nudge and your interest - added an MIT license.
