### ISSUE TITLE
Songs in "Your Music" aren't exported

### ISSUE THREAD

**Issue by jpulgarin** [caseychu/spotify-backup#8]

**Comment by evertvr** [comment]
You can modify the script with this piece of code:

    savedTracks = spotify.list('me/tracks', {'limit': 50, 'offset' : 0})
    with codecs.open(args.file, 'w', 'utf-8') as f:
        for indx, savedTrack in enumerate(savedTracks):
	    f.write(u'{index};{name};{artists};{album};{uri};{added}\r\n'.format(index=indx,
		uri=savedTrack['track']['uri'],
		name=savedTrack['track']['name'],
	        artists='| '.join([artist['name'] for artist in savedTrack['track']['artists']]),
		album=savedTrack['track']['album']['name'],
		added=savedTrack['added_at']))

Also, make sure when you authorize your application, that you use this scope `user-library-read playlist-read-private user-follow-read`

**Comment by jpulgarin** [comment]
Thanks @evertvr! Worked perfectly.

**Comment by NicoWeio** [comment]
So if the code already exists, shouldn't somebody implement this?

**Comment by evertvr** [comment]
@NicoWeio if you like, you can submit a pull request!

**Comment by NicoWeio** [comment]
Unfortunately, I am not familiar with Python.

**Comment by AwesomeLemon** [comment]
Unfortunately the 'me/tracks' link doesn't work anymore. I've tried to brute-force a new version to no avail. 

However, there's a workaround: just add all your liked songs to a new playlist, and run the script afterwards - it'll save this ordinary playlist without any problems. (also, when creating this playlist by selecting everything with Ctrl+A, don't forget to scroll to the bottom in order for everything to load).

**Comment by lamorton** [comment]
I have a [PR](https://github.com/caseychu/spotify-backup/pull/21) that would close this.

**Comment by Sogolumbo** [comment]
Another alternative pull request: #24

**Comment by caseychu** [comment]
Thanks for the contributions! You can now include Liked Songs using `--dump=liked,playlists`.
